server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: application-group
    topics:
      new-topic: NEW
      rejected-topoic: REJECTED
      withdrawn-topic: WITHDRAWN


  clients:
    vacancy-service:
      name: vacancy-service
      url: http://localhost:8083
    user-service:
      name: user-service
      url: http://localhost:8082

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5437/applicationdb
    username: applicationuser
    password: applicationpass
  jpa:
    hibernate:
      ddl-auto: none